[project]
name = "conjure_3d_ai"
version = "0.1.0"
description = "Conjure - Blender Add-on"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.56.0",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
