[project]
name = "conjure-addon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blender>=1.4",
    "google-genai>=1.56.0",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
